# Generated by Django 5.1 on 2024-09-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('localizacion', models.CharField(max_length=255)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
