# Generated by Django 5.0 on 2024-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
